openapi: 3.0.3
info:
  title: School Management API
  description: API for managing groups and students in a school.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/TsilavinaANDRIAMIHARISON/Library_Management_API/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /groups:
    get:
      summary: Retrieve groups
      parameters:
      - name: groupName
        in: query
        description: Filter by groups name
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: releaseDateStart
        in: query
        description: Filter groups with date (YYYY)
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: A list of groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
    put:
      summary: Update a group (idempotent)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        "200":
          description: Group updated successfully
    post:
      summary: Create a new group
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        "201":
          description: Group created successfully
    delete:
      summary: Delete a group
      parameters:
      - name: id
        in: query
        description: The ID of the group to delete
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "204":
          description: Group deleted successfully
  /students:
    get:
      summary: Retrieve students
      parameters:
      - name: group
        in: query
        description: Filter by groupName name
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    put:
      summary: Update an student (idempotent)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        "200":
          description: Student updated successfully
    post:
      summary: Create a new Student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        "201":
          description: Student created successfully
    delete:
      summary: Delete an student
      parameters:
      - name: id
        in: query
        description: The ID of the student to delete
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "204":
          description: Student deleted successfully
components:
  schemas:
    Group:
      required:
      - effectif
      - groupName
      - promotion
      - year
      type: object
      properties:
        id:
          type: string
        groupName:
          type: string
        year:
          type: string
          format: date
        promotion:
          type: string
        effectif:
          type: integer
    Student:
      required:
      - groupName
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
          - M
          - F
        birthDate:
          type: string
          format: date
        ref:
          type: string
        groupName:
          type: string
